[package]
name = "khaleesi"
version = "0.1.0"
authors = ["Nora <nora.widdecke@tu-bs.de>"]

[dependencies]
libc = "0.2.43"
chrono = "0.4"
itertools = "0.7.8"
log = "0.4.5"
simple_logger = "1.0.1"
yansi = "0.4.0"
indoc = "0.2.8"
