jobs:
  build:
    docker:
      - image: puzzlewolf/rust-libical3:0.2

    steps:
      - checkout
      - restore_cache:
          key: project-cache

      - run:
          name: Build
          command: cargo build
      - run:
          name: Running tests
          command: cargo test

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
