version: 2
jobs:
  cargo_fetch:
    docker:
      - image: puzzlewolf/rust-libical3:0.2
    working_directory: /mnt/crate
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v2-{{ checksum "Cargo.toml" }}-
            - cargo-v2-
      - run: cargo update
      - run: cargo fetch
      - persist_to_workspace:
          root: "."
          paths:
            - Cargo.lock
      - save_cache:
          key: cargo-v2-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/registry
            - ~/.cargo/git
  test:
    docker:
      - image: puzzlewolf/rust-libical3:0.2
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v2-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - target-v2-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test
          command: cargo test --verbose --frozen
          environment:
            # Need this for the coverage run
            RUSTFLAGS: "-C link-dead-code"
      - run:
          name: Prune the output files
          command: |
            for file in target/debug/* target/debug/.??*; do
              [ -d $file -o ! -x $file ] && rm -r $file
            done
      - save_cache:
          key: target-v2-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - ./target
      - persist_to_workspace:
          root: "."
          paths:
            - target/debug/*
  coverage:
    docker:
      - image: puzzlewolf/rust-libical3-kcov:0.2
        entrypoint: /bin/bash
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - run: mkdir target/coverage
      - run:
          name: Rerun the tests collecting coverage
          command: |
            for file in ./target/debug/*; do
              if test -x $file; then
                kcov --verify --exclude-pattern=tests \
                    target/coverage/$(basename $file) \
                  $file --quiet
              fi
            done
            kcov --merge target/coverage-merged target/coverage/*
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - store_artifacts:
          path: target/coverage-merged
          destination: coverage-merged
      - persist_to_workspace:
          root: "."
          paths:
            - target/coverage
  codecov_upload:
    docker:
      - image: buildpack-deps:curl
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test_all_and_coverage:
    jobs:
      - cargo_fetch
      - test:
          requires:
            - cargo_fetch
      - coverage:
          requires:
            - test
      - codecov_upload:
          requires:
            - coverage
